podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "6060"
image:
  tag: "ec519aee7854435036cee0c9a31dd1ec5bafd987"
egressd:
  conntrack: "nf"
tolerations:
  - key: scheduling.cast.ai/spot
    operator: Exists
