{{- if .Values.castai.clusterID }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "egressd.aggregator.fullname" . }}
  labels:
    {{- include "egressd.aggregator.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: api
      port: 8686
      protocol: TCP
      targetPort: 8686
    - name: prom-exporter
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: vector
      port: 6000
      protocol: TCP
      targetPort: 6000
  selector:
    {{- include "egressd.aggregator.selectorLabels" . | nindent 4 }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "egressd.aggregator.fullname" . }}
  labels:
    {{- include "egressd.aggregator.labels" . | nindent 4 }}
spec:
  replicas: 1
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      {{- include "egressd.aggregator.selectorLabels" . | nindent 4 }}
  serviceName: {{ include "egressd.aggregator.fullname" . }}-headless
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/aggregator-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "egressd.aggregator.labels" . | nindent 4 }}
    spec:
      serviceAccountName: {{ include "egressd.serviceAccountName" . }}
      dnsPolicy: ClusterFirst
      containers:
        - name: vector
          image: "timberio/vector:0.27.0-distroless-libc"
          imagePullPolicy: IfNotPresent
          args:
            - --config-dir
            - /etc/vector/
          env:
            - name: CASTAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{- include "egressd.fullname" }}
                  key: API_KEY
                  optional: true
          ports:
            - name: api
              containerPort: 8686
              protocol: TCP
            - name: prom-exporter
              containerPort: 9090
              protocol: TCP
            - name: vector
              containerPort: 6000
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: "/vector-data-dir"
            - name: config
              mountPath: "/etc/vector/"
              readOnly: true
      terminationGracePeriodSeconds: 3
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          projected:
            sources:
              - configMap:
                  name: {{ include "egressd.aggregator.fullname" . }}
{{- end}}